DROP TABLE IF EXISTS FLIGHTS;
DROP TABLE IF EXISTS AIRCRAFT;
DROP TABLE IF EXISTS BOOKINGS;

CREATE TABLE FLIGHTS(
    flightId INT AUTO_INCREMENT PRIMARY KEY,
    flights VARCHAR(250) NOT NULL,
    fro VARCHAR(250) NOT NULL,
    too VARCHAR(250) NOT NULL,
    dep VARCHAR(250) NOT NULL,
    drr VARCHAR(250) NOT NULL,
    aircraft VARCHAR(250) NOT NULL);



CREATE TABLE AIRCRAFT(
    aircraftId INT AUTO_INCREMENT PRIMARY KEY,
    aircraft_ VARCHAR(250) NOT NULL,
    model_ VARCHAR(250) NOT NULL,
    seats_ VARCHAR(250) NOT NULL,
    built_ VARCHAR(250) NOT NULL,
    service_ VARCHAR(250) NOT NULL
);


CREATE TABLE SEATS(
    seatId INT AUTO_INCREMENT PRIMARY KEY,
    aircraft_ VARCHAR(250) NOT NULL,
    row_ VARCHAR(250) NOT NULL,
    seat_ VARCHAR(250) NOT NULL,
    type_ VARCHAR(250) NOT NULL,
    class_ VARCHAR(250) NOT NULL
);


CREATE TABLE BOOKINGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Flight_ VARCHAR(250) NOT NULL,
    Datim VARCHAR(250) NOT NULL,
    Passenger_ VARCHAR(250) NOT NULL,
    Row_ VARCHAR(250) NOT NULL,
    Seat_ VARCHAR(250) NOT NULL,
    BookingId_ VARCHAR(250) NOT NULL

);
ALTER TABLE BOOKINGS
ADD FOREIGN KEY (Flight_)
REFERENCES FLIGHTS(flightId);

//ALTER TABLE BOOKINGS
//ADD FOREIGN KEY (Row_)
//REFERENCES SEATS();

ALTER TABLE BOOKINGS
ADD FOREIGN KEY (Seat_)
REFERENCES SEATS(seatId);

ALTER TABLE FLIGHTS
    ADD FOREIGN KEY (aircraft)
        REFERENCES AIRCRAFT(aircraftId);

ALTER TABLE SEATS
ADD FOREIGN KEY (aircraft_)
REFERENCES AIRCRAFT(aircraftId);